INSERT INTO Actions (Ccode, Aname, Point_Value, Priority, Required)
VALUES ('1', 'Animals in the Community Education', 10, '0', '0'),
('1', 'Companion Animal Management Pledge', 5, '0', '0'),
('1', 'Companion Animal Management Plan', 10, '0', '0'),
('1', 'Enhanced Licensing Compliancem', 5, '0', '0'),
('1', 'Pledge Supporting NJ Wildlife Action Plan', 10, '0', '0'),
('1', 'Wildlife Interaction Plan', 10, '0', '0'),
('2', 'Establish a Creative Team', 10, '0', '0'),
('2', 'Creative Assets Inventory', 10, '0', '0'),
('2', 'Creative Placemaking Plan', 10, '0', '0'),
('2', 'Municipal Commitments to Support Arts and Creative Culture', 5, '0', '0'),
('2', 'Utilizing Your Creative Assets', 10, '0', '0'),
('3', 'Brownfields Inventory & Prioritization', 10, '0', '0'),
('3', 'Brownfields Reuse Planning', 5, '0', '0'),
('3', 'Brownfields Marketing', 10, '0', '0'),
('3', 'Brownfields Assessment & Investigation', 5, '0', '0'),
('4', 'Create Green Team', 10, '0', '1'),
('4', 'Community Education and Outreach', 5, '0', '0'),
('4', 'Green Challenges', 10, '0', '0'),
('4', 'Hold a Green Fair', 10, '0', '0'),
('4', 'Green" Your Green Fair', 10, '0', '0'),
('5', 'Diversity on Boards & Commissions', 10, '1', '0'),
('5', 'Environmental Justice in Planning & Zoning', 10, '0', '0'),
('5', 'Lead Education and Outreach Programs', 10, '0', '0'),
('6', 'Climate Adaptation: Flooding Risk', 20, '1', '0'),
('6', 'Coastal Vulnerability Assessment', 20, '0', '0'),
('6', 'Extreme Temperature Event Plan', 10, '0', '0'),
('6', 'Heat Island Assessment', 10, '0', '0'),
('6', 'Community Wildfire Protection Plans', 10, '0', '0'),
('6', 'Firewise Community', 5, '0', '0'),
('6', 'Ready Set GO! Fire Company', 5, '0', '0'),
('6', 'Wildfire Safety Council', 10, '0', '0'),
('6', 'Emergency Communications Planning', 15, '0', '0'),
('6', 'Vulnerable Populations Identification for Emergencies', 10, '0', '0'),
('7', 'Energy Efficiency for Municipal Facilities', 5, '1', '0'),
('7', 'Energy Tracking and Management', 10, '1', '0'),
('7', 'Buy Electricity From A Renewable Source', 10, '0', '0'),
('7', 'Municipal On-Site Solar System', 10, '0', '0'),
('7', 'Municipal Geothermal Energy System', 10, '0', '0'),
('7', 'Municipal Wind Energy System', 10, '0', '0'),
('7', 'Renewable Government Energy Aggregation', 5, '0', '0'),
('7', 'Commercial Energy Efficiency Outreach', 10, '0', '0'),
('7', 'Residential Energy Efficiency Outreach', 10, '0', '0'),
('7', 'Make Your Town Solar Friendly', 15, '0', '0'),
('7', 'Community-Led Solar Initiatives', 5, '0', '0'),
('7', 'Wind Ordinance', 10, '0', '0'),
('7', 'Fleet Inventory', 10, '1', '0'),
('7', 'Meet Target for Green Fleets', 30, '0', '0'),
('7', 'Purchase Alternative Fuel Vehicles', 5, '0', '0'),
('7', 'Public Electric Vehicle Charging Infrastructure', 15, '0', '0'),
('7', 'Make Your Town Electric Vehicle Friendly', 15, '0', '0'),
('8', 'Farmland Preservation Plans', 10, '0', '0'),
('8', 'Community Gardens', 10, '0', '0'),
('8', 'Buy Fresh Buy Local Programs', 10, '0', '0'),
('8', 'Farmers Markets', 10, '0', '0'),
('8', 'Making Farmers Markets Accessible', 5, '0', '0'),
('9', 'Green Building Policy/Resolution', 5, '0', '0'),
('9', 'Green Building Training', 5, '0', '0'),
('9', 'Create a Green Development Checklist', 10, '0', '0'),
('9', 'Green Building Education', 5, '0', '0'),
('9', 'New Construction', 20, '0', '0'),
('9', 'Upgrade/Retrofit-Light Pollution', 10, '0', '0'),
('9', 'Upgrade/Retrofit-Water Conservation', 10, '0', '0'),
('10', 'Anti-Idling Education & Enforcement Program', 10, '0', '0'),
('10', 'Building Healthier Communities', 5, '0', '0'),
('10', 'Health in All Policies Professional Development', 10, '0', '0'),
('10', 'Private Well Outreach and Testing', 10, '0', '0'),
('10', 'Removing Lead in Drinking Water', 10, '0', '0'),
('10', 'Safe Routes to School', 10, '0', '0'),
('10', 'Smoke-Free and Tobacco-Free Public Places', 10, '0', '0'),
('11', 'Innovative Community Project 1', 10, '0', '0'),
('11', 'Innovative Community Project 2', 10, '0', '0'),
('11', 'Innovative Community Project 3', 10, '0', '0'),
('12', 'Sustainable Land Use Pledge', 10, '1', '0'),
('12', 'Build-Out Analysis', 10, '0', '0'),
('12', 'Bicycle and Pedestrian Audits', 5, '0', '0'),
('12', 'Bicycle and or Pedestrian Plan', 10, '0', '0'),
('12', 'Adopt a Complete Streets Policy', 10, '0', '0'),
('12', 'Institute Complete Streets', 10, '0', '0'),
('12', 'Effective Parking Management', 10, '0', '0'),
('12', 'Green Infrastructure Planning', 5, '0', '0'),
('12', 'Green Infrastructure Implementation', 10, '0', '0'),
('12', 'Enhanced Stormwater Management Control Ordinance', 10, '0', '0'),
('12', 'Green Building and Environmental Sustainability Element', 10, '0', '0'),
('12', 'Historic Preservation Element', 10, '0', '0'),
('12', 'Smart Workplaces', 5, '0', '0'),
('12', 'Transit-Oriented Development Supportive Zoning', 20, '0', '0'),
('13', 'Green Business Recognition Program', 10, '1', '0'),
('13', 'Green Jobs/Economic Development', 10, '0', '0'),
('13', 'Buy Local Campaign', 10, '0', '0'),
('13', 'Support Local Businesses', 10, '0', '0'),
('14', 'Natural Resource Inventory', '20', '1', '0'),
('14', 'Water Conservation Ordinance', 20, '1', '0'),
('14', 'Environmental Commission', 10, '0', '0'),
('14', 'Environmental Commission Site Plan Review', 10, '0', '0'),
('14', 'Open Space Plans', 10, '0', '0'),
('14', 'Water Conservation Education Program', 10, '0', '0'),
('14', 'Easement Inventory and Outreach', 10, '0', '0'),
('14', 'Easement Inspections and Evaluations', 15, '0', '0'),
('14', 'Clustering Ordinance', 10, '0', '0'),
('14', 'Environmental Assessment Ordinance', 10, '0', '0'),
('14', 'Habitat Conservation Ordinance', 10, '0', '0'),
('14', 'Tree Protection Ordinance', 10, '0', '0'),
('14', 'Community Forestry Management Plan and NJUCF Accreditation', 10, '0', '0'),
('14', 'Tree Hazard Inventory', 10, '0', '0'),
('14', 'Tree Maintenance Programs', 10, '0', '0'),
('14', 'Tree Planting Programs', 10, '0', '0'),
('15', 'Adopt a Green Purchasing Policy by Ordinance', 10, '0', '0'),
('15', 'Adopt a Green Purchasing Policy by Resolution', 5, '0', '0'),
('15', 'Green Cleaning Products', 10, '0', '0'),
('15', 'Green Maintenance Equipment and Materials', 10, '0', '0'),
('15', 'Recycled Paper', 10, '0', '0'),
('15', 'Green Grounds & Maintenance Policy', 10, '0', '0'),
('15', 'Efficient Landscape Design', 10, '0', '0'),
('15', 'Integrated Pest Management', 10, '0', '0'),
('15', 'Minimize Water Consumption', 10, '0', '0'),
('15', 'Recycled Materials and Composting', 10, '0', '0'),
('16', 'Municipal Communications Strategy', 10, '0', '0'),
('16', 'Improve Public Engagement in Municipal Government', 10, '0', '0'),
('16', 'Improve Public Engagement in Planning and Zoning', 10, '0', '0'),
('16', 'Online Municipal Public Service Systems', 10, '0', '0'),
('16', 'Digitizing Public Information', 10, '0', '0'),
('16', 'Open Data Inventory and Management', 10, '0', '0'),
('17', 'Municipal Carbon Footprint', 10, '1', '0'),
('17', 'Community Carbon Footprint', 10, '0', '0'),
('17', 'Climate Action Plan', 10, '0', '0'),
('17', 'Community Asset Mapping', 10, '0', '0'),
('17', 'Community Visioning', 10, '0', '0'),
('17', 'Vision Statement and Goals', 5, '0', '0'),
('17', 'Indicators and Targets', 10, '0', '0'),
('17', 'Action Plans', 10, '0', '0'),
('18', 'Prescription Drug Safety and Disposal', 10, '1', '0'),
('18', 'Recycling and Waste Reduction Education and Compliance', 15, '1', '0'),
('18', 'Commercial & Institutional Recycling', 10, '0', '0'),
('18', 'Community Paper Shredding Day', 5, '0', '0'),
('18', 'Construction and Demolition Waste Recycling', 5, '0', '0'),
('18', 'Food Waste', 10, '0', '0'),
('18', 'Household Hazardous Waste', 5, '0', '0'),
('18', 'Non-Mandated Materials Recycling', 5, '0', '0'),
('18', 'Recycling Depot', 10, '0', '0'),
('18', 'Backyard Composting Program', 5, '0', '0'),
('18', 'EPA WasteWise Partner', 5, '0', '0'),
('18', 'Grass - Cut It and Leave It Program', 5, '0', '0'),
('18', 'Materials Reuse Program', 10, '0', '0'),
('18', 'Pay-As-You-Throw Program', 10, '0', '0'),
('18', 'Reusable Bag Education Program', 5, '0', '0'),
('18', 'Waste Audit of Municipal Buildings or Schools', 10, '0', '0'),
('11', 'Raingardens', 10, '0', '0'),
('15', 'Adopt Behavioral Policies', 5, '0', '0'),
('4', 'Energy Education Outreach', 10, '0', '0'),
('9', 'Site Plan Green Design Standards', 20, '0', '0'),
('12', 'Complete Streets Programs', 20, '0', '0'),
('14', 'i-Tree Assessment of Municipal Trees', 10, '0', '0'),
('5', 'Lead-Safe Training Programs', 10, '0', '0'),
('18', 'Bulky Rigid Plastics', 10, '0', '0'),
('7', 'Driver Training', 10, '0', '0'),
('7', 'Vehicle Conversions', 10, '0', '0');
